apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: network-lab
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: python:3.12-alpine
          command:
            - sh
            - -c
            - |
              mkdir -p /tmp/www
              echo "Frontend is working" > /tmp/www/index.html
              python3 -m http.server 5678 --directory /tmp/www
